// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoASEa6DW7zzqQ53ZDiXFtbg9lbDO0-hA',
    appId: '1:973818913219:web:609c4c7a5eaf978c02dd76',
    messagingSenderId: '973818913219',
    projectId: 'firstapp-6747bdaa',
    authDomain: 'firstapp-6747bdaa.firebaseapp.com',
    storageBucket: 'firstapp-6747bdaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjNQW94RNlsQVQuL7Wlv8CY_bFEkqxO8w',
    appId: '1:973818913219:android:733d8c2d65ffa3e602dd76',
    messagingSenderId: '973818913219',
    projectId: 'firstapp-6747bdaa',
    storageBucket: 'firstapp-6747bdaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfGD_xsw7jT781PpO6z_3gLWZwrKP85Fk',
    appId: '1:973818913219:ios:efb9df632a8b626502dd76',
    messagingSenderId: '973818913219',
    projectId: 'firstapp-6747bdaa',
    storageBucket: 'firstapp-6747bdaa.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfGD_xsw7jT781PpO6z_3gLWZwrKP85Fk',
    appId: '1:973818913219:ios:efb9df632a8b626502dd76',
    messagingSenderId: '973818913219',
    projectId: 'firstapp-6747bdaa',
    storageBucket: 'firstapp-6747bdaa.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoASEa6DW7zzqQ53ZDiXFtbg9lbDO0-hA',
    appId: '1:973818913219:web:5e1bde2c452b30c802dd76',
    messagingSenderId: '973818913219',
    projectId: 'firstapp-6747bdaa',
    authDomain: 'firstapp-6747bdaa.firebaseapp.com',
    storageBucket: 'firstapp-6747bdaa.firebasestorage.app',
  );
}
